trigger:
- master

pool:
  name: 'SelfHostedAgents_ms'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.x'

- script: dotnet --list-sdks
  displayName: 'Check Installed .NET SDKs'

- script: |
    dotnet clean "$(Build.SourcesDirectory)/ClassLibraryProjects.sln" --configuration $(buildConfiguration)
  displayName: 'Clean Solution'


- task: DotNetCoreCLI@2
  displayName: 'Restore using dotnet CLI'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringLibrary.csproj'
    configuration: '$(buildConfiguration)'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '1'
    patchVersion: '$(Build.BuildId)'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package to Azure Artifacts'
  inputs:
    command: 'push'
    publishVstsFeed: 'Lab 4 – Azure DevOps CI CD/MyNuGetFeed'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    arguments: '--skip-duplicate'
